package com.azizbek.mygithub.model

import com.google.gson.annotations.SerializedName


data class Items (
 var id : Int,
 var nodeId : String,
 var name : String,
 var fullName : String,
 var private : Boolean,
 var owner : Owner,
 @SerializedName("html_url") var htmlUrl : String,
 var description : String,
 var fork : Boolean,
 var url : String,
 var forksUrl : String,
 var keysUrl : String,
 var collaboratorsUrl : String,
 var teamsUrl : String,
 var hooksUrl : String,
 var issueEventsUrl : String,
 var eventsUrl : String,
 var assigneesUrl : String,
 var branchesUrl : String,
 var tagsUrl : String,
 var blobsUrl : String,
 var gitTagsUrl : String,
 var gitRefsUrl : String,
 var treesUrl : String,
 var statusesUrl : String,
 var languagesUrl : String,
 var stargazersUrl : String,
 var contributorsUrl : String,
 var subscribersUrl : String,
 var subscriptionUrl : String,
 var commitsUrl : String,
 var gitCommitsUrl : String,
 var commentsUrl : String,
 var issueCommentUrl : String,
 var contentsUrl : String,
 var compareUrl : String,
 var mergesUrl : String,
 var archiveUrl : String,
 var downloadsUrl : String,
 var issuesUrl : String,
 var pullsUrl : String,
 var milestonesUrl : String,
 var notificationsUrl : String,
 var labelsUrl : String,
 var releasesUrl : String,
 var deploymentsUrl : String,
 var createdAt : String,
 var updatedAt : String,
 var pushedAt : String,
 var gitUrl : String,
 var sshUrl : String,
 var cloneUrl : String,
 var svnUrl : String,
 var homepage : String,
 var size : Int,
 @SerializedName("stargazers_count") var stargazersCount : Int,
 @SerializedName("watchers_count")var watchersCount : Int,
 @SerializedName("language")var language : String,
 var hasIssues : Boolean,
 var hasProjects : Boolean,
 var hasDownloads : Boolean,
 var hasWiki : Boolean,
 var hasPages : Boolean,
 var forksCount : Int,
 var mirrorUrl : String,
 var archived : Boolean,
 var disabled : Boolean,
 var openIssuesCount : Int,
 var license : License,
 var forks : Int,
 var openIssues : Int,
 var watchers : Int,
 var defaultBranch : String,
 var score : Int

)